al nconfig='nano /etc/nixos/configuration.nix'
al nhconfig='nano /etc/nixos/hardware-configuration.nix'
al nrb='nixos-rebuild boot'
al nrs='nixos-rebuild switch'
al ncg='nix-collect-garbage -d'
al ns='nix search nixpkgs'
